// Vue/todo-list/src/components/TodoItem.vue
<template>
    <div class="list-group-item" v-bind:class="{ 'list-group-item-success': todo.done }">
        <div>
            {{ todo.label }}

            <div class="float-right">
                <button class="btn btn-sm btn-outline-success" @click="$emit('done', todo.id)" v-if="!todo.done">Done</button>
                &nbsp;
                <button class="btn btn-sm btn-outline-danger" @click="$emit('remove', todo.id)">&times;</button>
            </div>
        </div>
        <div class="text-muted small">
            {{ todo.dateAdded.toLocaleDateString(language) }} {{ todo.dateAdded.getHours() }}:{{ todo.dateAdded.getMinutes() }}
        </div>
    </div>
</template>

<script>
    export default {
        name: 'TodoItem',
        data() {
            return {
                language: window.navigator.language
            }
        },
        props: {
            todo: {
                type: Object
            }
        }
    }
</script>

// React/todo-list/src/components/Todo/TodoItem.js
import React, {Component} from 'react';

class TodoItem extends Component {

    render() {
        return (
            <li className={"list-group-item " + (this.props.item.done ? "list-group-item-success" : "")}>
                <div>
                    {this.props.item.label}

                    <div className="float-right">
                        {!this.props.item.done ? <button className="btn btn-sm btn-outline-success" onClick={this.props.done} data-index={this.props.index}>Done</button> : "" }
                        &nbsp;
                        <button className="btn btn-sm btn-outline-danger" data-index={this.props.index} onClick={this.props.remove}>&times;</button>
                    </div>
                </div>
                <div className="text-muted small">
                    {this.props.item.dateAdded.toLocaleDateString(window.navigator.language)} {this.props.item.dateAdded.getHours()}:{this.props.item.dateAdded.getMinutes()}
                </div>
            </li>
        )
    }
}

export default TodoItem;
