// Angular/todo-list/src/app/todo/todo.component.ts
import {Component, OnInit} from '@angular/core';
import {TodoItem} from '../todo-item';

let newId = 0;

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.css']
})
export class TodoComponent implements OnInit {
  items: TodoItem[] = [];
  newItemValue = '';
  constructor() {
    this.markDone = this.markDone.bind(this);
    this.removeItem = this.removeItem.bind(this);
    this.addItem = this.addItem.bind(this);
  }

  ngOnInit() {
  }

  addItem() {
    this.items.push(new TodoItem(newId++, this.newItemValue, false, new Date()));
    this.newItemValue = '';
  }

  markDone(item: TodoItem) {
    const index = this.items.indexOf(item);
    this.items[index] = new TodoItem(
      item.id,
      item.label,
      true,
      item.dateAdded
    );
  }

  removeItem(item: TodoItem) {
    const index = this.items.indexOf(item);
    this.items = [
      ...this.items.slice(0, index),
      ...this.items.slice(index + 1)
    ];
  }

}

<div>
  <h1>Todo List</h1>
  <div class="input-group mb-3">
    <input type="text"
           class="form-control"
           placeholder="Todo Item"
           aria-label="Todo Item"
           aria-describedby="basic-addon2"
           [(ngModel)]="newItemValue"
           (keyup.enter)="addItem()"
    />
    <div class="input-group-append">
      <button class="btn btn-outline-primary" type="button" (click)="addItem()">Button</button>
    </div>
  </div>
  <div >
    <app-todo-item *ngFor="let item of items" [item]="item" [onDone]="markDone" [onRemove]="removeItem"></app-todo-item>
  </div>
</div>

// React/todo-list/src/components/Todo/Todo.js
import React, { Component } from 'react';
import TodoItem from './TodoItem';

class Todo extends Component {
    constructor(props) {
        super(props);


        this.state = {items: [], text: ""};
        this.addItem = this.addItem.bind(this);
        this.handleChange = this.handleChange.bind(this);
        this.markItemDone = this.markItemDone.bind(this);
        this.removeItem = this.removeItem.bind(this);
        this.checkEnter = this.checkEnter.bind(this);
    }

    render() {
        return (
            <div>
                <h1>Todo List</h1>
                <div className="input-group mb-3">
                    <input type="text"
                           className="form-control"
                           placeholder="Todo Item"
                           aria-label="Todo Item"
                           aria-describedby="basic-addon2"
                           onChange={this.handleChange}
                           value={this.state.text}
                           onKeyPress={this.checkEnter}
                    />
                        <div className="input-group-append">
                            <button onClick={this.addItem} className="btn btn-outline-primary" type="button">Button</button>
                        </div>
                </div>
                <div >
                    {this.state.items.map((item, index) => <TodoItem key={index} index={index} item={item} done={this.markItemDone} remove={this.removeItem} />)}
                </div>
            </div>

        )
    }

    addItem() {
        const item = {
            label: this.state.text,
            done: false,
            dateAdded: new Date()
        };
        this.setState({...this.state, items: [...this.state.items, item], text: ""});
    }

    markItemDone(e) {
        const index = Number(e.target.getAttribute("data-index"));
        this.setState(
            {...this.state,
                items: [
                    ...this.state.items.slice(0, index),
                    {
                        ...this.state.items[index]
                        , done: true
                    },
                    ...this.state.items.slice(index + 1)
                ]
            }
        );
    }

    removeItem(e) {
        const index = Number(e.target.getAttribute("data-index"));
        this.setState(
            {...this.state,
                items: [
                    ...this.state.items.slice(0, index),
                    ...this.state.items.slice(index + 1)
                ]
            }
        );
    }


    handleChange(e) {
        this.setState({...this.state, text: e.target.value});
    }

    checkEnter(e) {
        if (e.key === 'Enter')
        {
            this.addItem();
        }
    }
}

export default Todo;
