// Angular/todo-list/src/app/todo-item/todo-item.component.ts
import {Component, HostBinding, Input, OnChanges, OnInit} from '@angular/core';
import {TodoItem} from '../todo-item';


@Component({
  selector: 'app-todo-item',
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.css'],
  host: {'class': 'list-group-item'}
})

export class TodoItemComponent implements OnInit, OnChanges {

  @Input() item: TodoItem;
  @Input() onDone;
  @Input() onRemove;

  @HostBinding('class.list-group-item-success') isDone: boolean;

  constructor() { }

  ngOnInit() {
    this.isDone = this.item.done;
  }

  ngOnChanges(changes) {
    this.isDone = this.item.done;
  }

  done() {
    this.onDone(this.item);
  }

  remove() {
    this.onRemove(this.item);
  }

}

<div>
<div>
  {{item.label}}

  <div class="float-right">
    <button class="btn btn-sm btn-outline-success" (click)="done()" *ngIf="!item.done">Done</button>
    &nbsp;
    <button class="btn btn-sm btn-outline-danger" (click)="remove()">&times;</button>
  </div>
</div>
<div class="text-muted small">
  {{item.dateTimeString()}}
</div>
</div>

// Vue/todo-list/src/components/TodoItem.vue
<template>
    <div class="list-group-item" v-bind:class="{ 'list-group-item-success': todo.done }">
        <div>
            {{ todo.label }}

            <div class="float-right">
                <button class="btn btn-sm btn-outline-success" @click="$emit('done', todo.id)" v-if="!todo.done">Done</button>
                &nbsp;
                <button class="btn btn-sm btn-outline-danger" @click="$emit('remove', todo.id)">&times;</button>
            </div>
        </div>
        <div class="text-muted small">
            {{ todo.dateAdded.toLocaleDateString(language) }} {{ todo.dateAdded.getHours() }}:{{ todo.dateAdded.getMinutes() }}
        </div>
    </div>
</template>

<script>
    export default {
        name: 'TodoItem',
        data() {
            return {
                language: window.navigator.language
            }
        },
        props: {
            todo: {
                type: Object
            }
        }
    }
</script>
