// React/todo-list/src/components/App.js
import React, {Component} from 'react';
import Todo from './Todo/Todo';

class App extends Component {

    constructor() {
        super();
    }

    render() {
        return (
            <div>
                <div className="row justify-content-center">
                    <div className="col-4">
                        <Todo />
                    </div>
                </div>
            </div>
        );
    }

}

export default App;

// Vue/todo-list/src/App.vue
<template>
  <div id="app" class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-4">
        <Todo />
      </div>
    </div>
  </div>
</template>

<script>
import Todo from './components/Todo.vue'

export default {
  name: 'app',
  components: {
      Todo
  }
}
</script>
